### ISSUE TITLE
Unable to connect - Timeout error

### ISSUE THREAD

**Issue by smoneta** [heroku/kafka-helper#15]
While working with python 3, I have to make a small update in order to get the URLs properly but now I'm getting this error when trying to test it out:

```
Traceback (most recent call last):
  File "/Users/smoneta/soma/slackbot-fastlane-approvals/main_kafka.py", line 6, in <module>
    producer.send('test-topic', key='my key', value={'k': 'v'})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kafka/producer/kafka.py", line 576, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kafka/producer/kafka.py", line 702, in _wait_on_metadata
    raise Errors.KafkaTimeoutError(
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
```

Here is how the producer config looks like:
```
producer = KafkaProducer(
        bootstrap_servers=get_kafka_brokers(),
        security_protocol='SSL',
        ssl_context=get_kafka_ssl_context(),
        value_serializer=value_serializer,
        acks=acks,
        api_version=(2, 8, 1), <---- added by me since it was not even working without this.
        ssl_check_hostname=False <---- added by me since it was set to TRUE by default
    )
```

here is a `print` of the `producer.config`:
```
{'bootstrap_servers': ['ec2-34-234-254-237.compute-1.amazonaws.com:9096', 'ec2-18-233-203-149.compute-1.amazonaws.com:9096', 'ec2-18-204-41-222.compute-1.amazonaws.com:9096', 'ec2-35-173-52-55.compute-1.amazonaws.com:9096', 'ec2-35-173-23-89.compute-1.amazonaws.com:9096', 'ec2-18-232-24-85.compute-1.amazonaws.com:9096', 'ec2-34-236-112-122.compute-1.amazonaws.com:9096', 'ec2-34-232-227-0.compute-1.amazonaws.com:9096'], 'client_id': 'kafka-python-producer-1', 'key_serializer': None, 'value_serializer': <function <lambda> at 0x7ffd602555e0>, 'acks': -1, 'bootstrap_topics_filter': set(), 'compression_type': None, 'retries': 0, 'batch_size': 16384, 'linger_ms': 0, 'partitioner': <kafka.partitioner.default.DefaultPartitioner object at 0x7ffd602d8f10>, 'buffer_memory': 33554432, 'connections_max_idle_ms': 540000, 'max_block_ms': 60000, 'max_request_size': 1048576, 'metadata_max_age_ms': 300000, 'retry_backoff_ms': 100, 'request_timeout_ms': 30000, 'receive_buffer_bytes': None, 'send_buffer_bytes': None, 'socket_options': [(6, 1, 1)], 'sock_chunk_bytes': 4096, 'sock_chunk_buffer_count': 1000, 'reconnect_backoff_ms': 50, 'reconnect_backoff_max_ms': 1000, 'max_in_flight_requests_per_connection': 5, 'security_protocol': 'SSL', 'ssl_context': <ssl.SSLContext object at 0x7ffd901a66c0>, 'ssl_check_hostname': False, 'ssl_cafile': None, 'ssl_certfile': None, 'ssl_keyfile': None, 'ssl_crlfile': None, 'ssl_password': None, 'ssl_ciphers': None, 'api_version': (2, 8, 1), 'api_version_auto_timeout_ms': 2000, 'metric_reporters': [], 'metrics_num_samples': 2, 'metrics_sample_window_ms': 30000, 'selector': <class 'selectors.KqueueSelector'>, 'sasl_mechanism': None, 'sasl_plain_username': None, 'sasl_plain_password': None, 'sasl_kerberos_service_name': 'kafka', 'sasl_kerberos_domain_name': None, 'sasl_oauth_token_provider': None, 'compression_attrs': 0}
```

**Comment by smoneta** [comment]
`Update`: I forgot the PREFIX (from the heroku app config): 
```
producer.send('southplatte-36638.test-topic', key='my key', value={'k': 'v'})
```

but now getting:
```
Traceback (most recent call last):
  File "/Users/smoneta/soma/slackbot-fastlane-approvals/main_kafka.py", line 6, in <module>
    producer.send('southplatte-36638.test-topic', key='my key', value={'k': 'v'})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kafka/producer/kafka.py", line 584, in send
    assert type(key_bytes) in (bytes, bytearray, memoryview, type(None))
AssertionError
```
